version: '3'
services:
  redis:
    image: redis
    hostname: redis-container
    ports:
      - "6379:6379"
    networks:
      - pad_reexam
  api-gateway:
    image: razvanfiser/api-gateway
    ports:
      - "8080:8080"
    networks:
      - pad_reexam
  sports1:
    image: razvanfiser/sports-service
    hostname: sports1-container
    ports:
      - "5000:5000"
    networks:
      - pad_reexam
  sports2:
    image: razvanfiser/sports-service
    hostname: sports2-container
    ports:
      - "5001:5000"
    networks:
      - pad_reexam
  sports3:
    image: razvanfiser/sports-service
    hostname: sports3-container
    ports:
      - "5002:5000"
    networks:
      - pad_reexam
  imgur1:
    image: razvanfiser/imgur-service
    hostname: imgur1-container
    ports:
      - "5003:5000"
    networks:
      - pad_reexam
  imgur2:
    image: razvanfiser/imgur-service
    hostname: imgur2-container
    ports:
      - "5004:5000"
    networks:
      - pad_reexam
  imgur3:
    image: razvanfiser/imgur-service
    hostname: imgur3-container
    ports:
      - "5005:5000"
    networks:
      - pad_reexam
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    volumes:
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - "3000:3000"
  sports-db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
        POSTGRES_PASSWORD: mysecretpassword
        POSTGRES_USER: admin
        POSTGRES_DB: sports_db
    hostname: sports-db
    networks:
      - pad_reexam
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
  imgur-db:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: admin
      POSTGRES_DB: imgur_db
    hostname: imgur-db
    networks:
      - pad_reexam
    volumes:
      - ./init-scripts-imgur:/docker-entrypoint-initdb.d
networks:
  pad_reexam:
    external:
      name: pad_reexam