version: '3'
services:
  sports1:
    image: sports-service
    hostname: sports1-container
    ports:
      - "5000:5000"
    networks:
      - pad_reexam
  sports2:
    image: sports-service
    ports:
      - "5001:5000"
  imgur1:
    image: imgur-service
    ports:
      - "5003:5000"
    networks:
      - pad_reexam
  imgur2:
    image: imgur-service
    ports:
      - "5004:5000"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    volumes:
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
      - "3000:3000"
  sports-db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
        POSTGRES_PASSWORD: mysecretpassword
        POSTGRES_USER: admin
        POSTGRES_DB: sports_db
    hostname: sports-db
    networks:
      - pad_reexam
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
  imgur-db:
    image: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: admin
      POSTGRES_DB: imgur_db
    hostname: imgur-db
    networks:
      - pad_reexam
    volumes:
      - ./init-scripts-imgur:/docker-entrypoint-initdb.d
networks:
  pad_reexam:
    external:
      name: pad_reexam